-- CRM order history: keep customer address fields and product snapshots stable.
ALTER TABLE "Order" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "city" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "postalCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "productNameEn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "brand" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "colorHex" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "specialBoxAvailable" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "specialBoxPrice" INTEGER NOT NULL DEFAULT 350000;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "withSpecialBox" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "specialBoxPrice" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "packagingLabel" TEXT NOT NULL DEFAULT 'جعبه عادی';
